### ISSUE TITLE
anyway to fetch the onform image when filling the form?

### ISSUE THREAD

**Issue by vst212** [vvd170501/python-gforms#8]

**Comment by vvd170501** [comment]
I don't think it's possible with the current implementation.

Image objects in form JSON have some kind of ID (see [this comment](https://github.com/vvd170501/python-gforms/blob/07ab4dd2b66426d9489efac8f5c63a799bfe520f/gforms/elements.py#L236) for more details), but I couldn't find a way to generate direct image links from these IDs.

**Comment by vst212** [comment]
![image](https://user-images.githubusercontent.com/47769540/192342965-439f6d71-af5a-40e0-90f0-9252eafdafcb.png)
Actually, I am doing something like google Forms has multi pages. The images are not in the first page. I have to complete the first few pages of the form by the bot and after that, the page will show up as an image. I would like to retrieve that shown image and OCR for that. Is it any alternative to get rig of this or any suggestion on that?

**Comment by vvd170501** [comment]
I don't really understand what you want to do with the image.
Why OCR? Do you need to copy some text from the image into a form input field? Or just extract images from all apges of the form?

**Comment by vst212** [comment]
I already have solutions on the remaining part, now remaining part is how to exact the image from multi section Google form.

**Comment by vst212** [comment]
Any possibility method that work like when image on the page either save to local files or have an url ?

**Comment by vvd170501** [comment]
Well, I guess the easiest way would be to just parse each page's HTML and extract links from `img` tags 
[Here](https://github.com/vvd170501/python-gforms/blob/07ab4dd2b66426d9489efac8f5c63a799bfe520f/gforms/form.py#L502), `last_response` is the page which comes after the submitted page.
E.g. if you submitted the first page, `last_response.text` will contain HTML for the second page of the form.

**Comment by vvd170501** [comment]
Solved in https://github.com/vvd170501/python-gforms/issues/9#issuecomment-1259320652, closing
