### ISSUE TITLE
Finally implement Image elements and attachments

### ISSUE THREAD

**Issue by vvd170501** [vvd170501/python-gforms#9]
Possible solutions:
1. Generate direct image link from cosmoId. Still not sure if this could actually work.
2. Just parse image tags from all form pages.
   See https://github.com/vvd170501/python-gforms/issues/8#issuecomment-1258478355
   Add `Form.resolve_images()` method to parse images only on-demand? (don't slow down multipage form loading)

**Comment by vst212** [comment]
type object 'Form' has no attribute 'resolve_images'

I am using the example.py for the base, where can I add the function or coding inside to make it possilbe?

Thank a lot as your help a lots

**Comment by vvd170501** [comment]
Image elements are still not implemented, guess I'll finish this in 1-2 weeks.

Right now you can fork the repository (or just edit your local copy of the package) and modify existing code in `Form.submit`. Something like this:
```diff
    def submit(
            self,
            session=None, *,
            need_receipt=False,
            captcha_handler: Optional[Callable[[requests.models.Response], str]] = None,
            emulate_history=False,
+           extract_image_links=False,
+   ) -> Optional[SubmissionResult]:
-   ) -> SubmissionResult:
@@...@@
            next_page = page.next_page()
+           # Don't send the last request (prevent actual form submission) if you only need to extract links
+           if next_page is None and extract_image_links:
+               return
            # solve the CAPTCHA to submit the form and send a receipt
            if need_receipt and next_page is None:
                captcha_response = captcha_handler(last_response)
            last_response = self._submit_page(session, page, history, draft,
                                              continue_=next_page is not None,
                                              need_receipt=need_receipt,
                                              captcha_response=captcha_response)
            soup = BeautifulSoup(last_response.text, 'html.parser')
+           if extract_image_links:
+               for tag in soup.find_all('img'):
+                   # Some additional filtering may be needed (e.g. filter by tag's class attribute or surrounding tags).
+                   if self._is_form_image(tag):
+                       # Don't forget to initialize self.image_links in `Form._clear`
+                       self.image_links.append(tag['src'])
            history = self._get_history(soup)
```

Then call `form.submit(extract_image_links=True)`, and images from the visited pages should be saved to `form.image_links`

**Comment by vst212** [comment]
It seems still has some problems as can the function be printed on every section page, The image is in the last section part before submitting and I am not sure where to insert it. Sorry for annoying you.

**Comment by vst212** [comment]
https://forms.gle/BwsRmC9jR3cbLZfG7
This is the sample for your easy understanding what I mean,

**Comment by vst212** [comment]
I have find out the solution by using the soup  filter in submit result. Finally done. Thanks a lot for your hints again.
